package constants

// 空值定义
var EMPTY_STR = ""
var EMPTY_TRUE = true
var EMPTY_FALSE = false
var MIN_DOUBLE float64 = 0.00000000001

// 常量
const TRANSACTION_KEY = "tranaction_tx"

type PERMISSION_KEY string

const (
	PERMISSION_KEY__DEMO PERMISSION_KEY = "goodshub-datacenter"
)

// 事件类型
type EVENT_TYPE string

// Redis 前缀Key常量
type REDIS_KEY string

// 告警类型 TODO
type LOG_ID string

const (
	LOG_ID__EVENT_HANDLE   LOG_ID = "EVENT_HANDLE"
	LOG_ID__COMMON         LOG_ID = "COMMON"
	LOG_ID__TRANSACTION    LOG_ID = "TRANSACTION"    // 事务
	LOG_ID__DATABASE_ERROR LOG_ID = "DATABASE_ERROR" // MYSQL 异常错误 *重要
	LOG_ID__REDIS_ERROR    LOG_ID = "FEDIS_ERROR"    // REDIS 异常错误 *重要
	LOG_ID__JSON_ENCODING  LOG_ID = "JSON_ENCODING"  // 序列化数据失败
	LOG_ID__PERMISSION     LOG_ID = "PERMISSION"     // 权限
)

type TIMER_TYPE string

// RESPONSE_TYPE 响应类型
type RESPONSE_TYPE int

// 常量的定义以客户端可能需要进行特殊处理为建立标准

const (
	// 空响应
	RESPONSE_TYPE__RESPONSE_UNKNOW RESPONSE_TYPE = -1

	// 正常响应
	RESPONSE_TYPE__RESPONSE_OK RESPONSE_TYPE = 0

	// 正常处理，但没有找到对应的数据
	RESPONSE_TYPE__RESPONSE_NO_DATA RESPONSE_TYPE = 10000

	// 用户参数校验失败
	RESPONSE_TYPE__RESPONSE_PARAM_INVALID RESPONSE_TYPE = 90400

	// 常规错误
	RESPONSE_TYPE__RESPONSE_ERROR RESPONSE_TYPE = 90000

	// 用户登录令牌无效，含过期
	RESPONSE_TYPE__RESPONSE_TOKEN_INVALID RESPONSE_TYPE = 90401

	// 没有接口权限
	RESPONSE_TYPE__RESPONSE_RBAC_INVALID RESPONSE_TYPE = 90403

	// Action无效
	RESPONSE_TYPE__RESPONSE_ACTION_INVALID RESPONSE_TYPE = 90404

	// AccessToken无效
	RESPONSE_TYPE__RESPONSE_ACCESS_TOKEN_INVALID RESPONSE_TYPE = 90407

	// 请求数超限被拒绝
	RESPONSE_TYPE__RESPONSE_REJECT RESPONSE_TYPE = 90429

	// 响应异常
	RESPONSE_TYPE__RESPONSE_CRASH RESPONSE_TYPE = 90500

	// 服务不可用
	RESPONSE_TYPE__RESPONSE_SERVICE_INVALID RESPONSE_TYPE = 90503
)
